### ISSUE TITLE
By Pull Request On Issue 14, a bug generated. 

### ISSUE THREAD

**Issue by Creatoon** [Creatoon/Jar-web-app#17]
issue #14 

**Describe the bug**
What happened is, anyone can delete anyone's message, and this shouldn't happend.

**Additional context**
What you can do to solve it, check if the user on the message is equal to the user gonna delete the message, if both are same then it should be deleted otherwise delete option should not be there.

**Comment by sanskarbansal** [comment]
Can you assign it to me ?

**Comment by Creatoon** [comment]
@sanskarbansal  go ahead.
