### ISSUE TITLE
add code of conduct

### ISSUE THREAD

**Issue by starlightknown** [Creatoon/Jar-web-app#25]
add code of conduct to the project

**Comment by nisha331** [comment]
As the project does not contain code of conduct file I would like to add it.
I am a LGMSOC'21 participant kindly assign it to me.

**Comment by Creatoon** [comment]
@nisha331 ok go ahead.

**Comment by nisha331** [comment]
Sent a PR kindly check it, and the issue is not assigned so assign it if neccesary.  
Thank you

**Comment by Creatoon** [comment]
@nisha331 Really appreciate you for this work, actually we don't assign issue to anyone, we simply follow first come and take policy.
