### ISSUE TITLE
Link Code of Conduct, License and Contribution Guidelines to Readme File

### ISSUE THREAD

**Issue by Shaishav0507** [Creatoon/Jar-web-app#30]
**Is your feature request related to a problem? Please describe.**
Hey @Creatoon 
I would like to link above mentioned files to the readme file as they are present in the branch but not linked to the readme file.
Please assign it to me.
Thanks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ayan-thecodeking** [comment]
I also want to contribute in this issue ..please assign me if needed anything to add 
i will be happy to  contribute in this 'thank you :) @Creatoon
