### ISSUE TITLE
Update the Readme.md file 

### ISSUE THREAD

**Issue by Baba-Yaga-1** [Creatoon/Jar-web-app#34]
The README.md file can be updated with contributors section and tech stacks.
Can you assign it ?

**Comment by 0xCipher-max** [comment]
I can do this Please assign me this issue

**Comment by Creatoon** [comment]
@0xCipher-max please find other issues, as @LizaHaddock asked for this issue first ,I am assigning the issue to @LizaHaddock

**Comment by Creatoon** [comment]
copy of #46
