### ISSUE TITLE
Add Timestamp when a new message is sent

### ISSUE THREAD

**Issue by Veeresh-Rex** [Creatoon/Jar-web-app#35]
**Is your feature request related to a problem? Please describe.**
I want to add a new feature. When a user send a message the time of that message is send shown in chat box like whatsapp or other messaging apps.
**Describe the solution you'd like**
I want to add timestamp of message.

**Additional context**
Please assign it under LGMSOC21.

**Comment by Creatoon** [comment]
@Veeresh-Rex go ahead

**Comment by Veeresh-Rex** [comment]
Getting error while preforming npm install 

### Error
npm ERR! code 1
npm ERR! path F:\LGM-SOC21\Jar-web-app\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild 
&& node install/dll-copy)
npm ERR! info sharp Using cached C:\Users\veeresh\AppData\Local\npm-cache\_libvips\libvips-8.10.0-win32-x64.tar.br
npm ERR! info sharp Creating F:\LGM-SOC21\Jar-web-app\node_modules\sharp\build\Release
npm ERR! info sharp Copying DLLs from F:\LGM-SOC21\Jar-web-app\node_modules\sharp\vendor\8.10.0\lib to F:\LGM-SOC21\Jar-web-app\node_modules\sharp\build\Release
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.16.3 | win32 | x64
npm ERR! gyp info find Python using Python version 3.8.2 found at "C:\Users\veeresh\AppData\Local\Programs\Python\Python38-32\python.exe"      
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS checking VS2017 (15.9.28307.1525) found at:
npm ERR! gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
npm ERR! gyp ERR! find VS - found "Visual Studio C++ core features"
npm ERR! gyp ERR! find VS - missing any VC++ toolset
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\veeresh\AppData\Roaming\nvm\v12.16.3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\Users\veeresh\AppData\Roaming\nvm\v12.16.3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\veeresh\AppData\Roaming\nvm\v12.16.3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Users\veeresh\AppData\Roaming\nvm\v12.16.3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Users\veeresh\AppData\Roaming\nvm\v12.16.3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Users\veeresh\AppData\Roaming\nvm\v12.16.3\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\veeresh\AppData\Roaming\nvm\v12.16.3\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
npm ERR! gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\veeresh\\AppData\\Roaming\\nvm\\v12.16.3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd F:\LGM-SOC21\Jar-web-app\node_modules\sharp
npm ERR! gyp ERR! node -v v12.16.3
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\veeresh\AppData\Local\npm-cache\_logs\2021-06-16T09_44_44_737Z-debug.log

**Comment by Creatoon** [comment]
Try running npm install
