### ISSUE TITLE
Add Let'sGrowMore logo under 'Open Source Program' section

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Creatoon/Jar-web-app#36]
Since this project is part of LGMSOC . I think it's good idea to showcase it in README.md file under Open Source Program section .
 will like to work on this issue under LGMSOC if maintainers agree
@Creatoon

**Comment by Creatoon** [comment]
@Ayan-thecodeking go ahead

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking go ahead

ok

**Comment by Creatoon** [comment]
@Ayan-thecodeking I don't think, this issue is relevant, as the readme should only contain details about the project, not about any program.
