### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [Creatoon/Jar-web-app#39]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@Creatoon pls assign this issue to me.

**Comment by ishitakapoor26** [comment]
Like this
![labels](https://user-images.githubusercontent.com/78542333/122367950-889ecb80-cf7a-11eb-9228-ebf202399b1a.PNG)

**Comment by Creatoon** [comment]
@ishitakapoor26 go for it
