### ISSUE TITLE
Add zoom in animation when buttons are hovered.

### ISSUE THREAD

**Issue by supzi-del** [Creatoon/Jar-web-app#45]
**Is your feature request related to a problem? Please describe.**
I would like to add a scale transform on buttons to make the page dynamic. I will work on it under LGMSOC

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Creatoon** [comment]
@supzi-del Can you please elaborate on how this feature will work.

**Comment by supzi-del** [comment]
https://user-images.githubusercontent.com/78655439/122599572-351ca280-d08c-11eb-9632-dbeec627934e.mp4

It's just the hover effect on buttons as shown

**Comment by Creatoon** [comment]
@supzi-del Just make sure you target every button
