### ISSUE TITLE
User is not able to delete message if text length is small.

### ISSUE THREAD

**Issue by sanskarbansal** [Creatoon/Jar-web-app#57]
**Describe the bug**
User is not able to delete the message if the length of text message is small.
**To Reproduce**
Steps to reproduce the behaviour:
1. Join a room
2. Send a message 'Hi'
3. That's It

**Expected behaviour**

It should show delete message option regardless of length of characters

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by Creatoon** [comment]
@sanskarbansal  As the website is not implemented on small devices, we will look into that thing later, So this issue can be solved by giving the message box a `minimum-width.

**Comment by RituCs** [comment]
I would like to work on this issue under LGMSOC21. Please assign to me.

**Comment by Creatoon** [comment]
@RituCs go ahead
