### ISSUE TITLE
Logo on landing page should be a link

### ISSUE THREAD

**Issue by supzi-del** [Creatoon/Jar-web-app#58]
**Is your feature request related to a problem? Please describe.**
Sites usually have the website itself linked when the user clicks on the logo

**Describe the solution you'd like**
I would like to add a href link so that when the logo is clicked, it takes back to the homepage.

**Describe alternatives you've considered**

**Additional context**

**Comment by supzi-del** [comment]
I would like to work on this under LGMSOC.

**Comment by Creatoon** [comment]
@supzi-del go ahead

**Comment by supzi-del** [comment]
Could you please assign and add label?

**Comment by Creatoon** [comment]
For now, we don't have any landing page, so this is unnecessary.
