### ISSUE TITLE
add some badges to the README file

### ISSUE THREAD

**Issue by Umesh-01** [Creatoon/Jar-web-app#62]
## Description
add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

## Describe the solution you'd like

![image](https://user-images.githubusercontent.com/83420185/124011646-de08bd00-d9fd-11eb-8efb-f494543c6c1a.png)

I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

### Work under/as

- [x] LGMSOC
- [ ] Contributor

**Comment by Umesh-01** [comment]
@Creatoon @aayushdubey2 Should I work on this??

**Comment by joshi-kaushal** [comment]
would love to contribute to this under LGMSOC

**Comment by Creatoon** [comment]
Irrelevant, as GitHub takes care of these features already.
